webapp/news/models.py
"""
В данном файле описан класс новостей: в базе данных хранятся id новости, абсолютная ссылка на неё, заголовок новости
время чтения новости, дата публикации новости, а также текст новости
"""


from webapp.db import db


class News(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.String, unique=True, nullable=False)
    title = db.Column(db.String, nullable=False)
    # поскольку время чтения - категориальный фильтр, то достаточно хранить его в виде одной буквы латинского
    # алфавита - S, если время чтения меньше пяти минут, M, если чтение занимает от пяти до десяти минут, и L,
    # если чтение занимает больше десяти минут
    read_time = db.Column(db.String(1), nullable=False)
    date = db.Column(db.DateTime, nullable=False)
    text = db.Column(db.Text)

    # функция позволяет получить время чтения для статьи, если оно не было получено с сайта, который мы парсили
    def get_read_time(self, value):
        if not value.isdigit():
            value = value.split()
            value = len(value) // 250
        value = int(value)
        if value < 5:
            self.read_time = 'S'
        elif value < 10:
            self.read_time = 'M'
        else:
            self.read_time = 'L'

    def __repr__(self):
        return f'Пост {self.id} - {self.title}'

webapp/news/views.py
"""
В данном файле реализованы основные функции, связанные с новостями: отображение всех новостей на главное странице,
отображение выбранной новости, категориальный фильтр по времени чтения новости
"""


from flask import Blueprint, abort, redirect, render_template, url_for
from flask_login import current_user
from webapp.news.models import News
from webapp.user.models import Favorite

blueprint = Blueprint('news', __name__)


@blueprint.route('/', )
def index():
    title = 'Новости'
    sorted_news = News.query.order_by(News.date.desc()).all()
    news = []
    if current_user.is_authenticated:
        favs_news = Favorite.query.filter(Favorite.user_id == current_user.id)
        for n in favs_news:
            news.append(n.news_id)
    return render_template(
        'index.html',
        title=title,
        posts=sorted_news,
        favs=news,
    )


@blueprint.route('/news/<int:news_id>')
def news_index(news_id):
    news = News.query.get(news_id)
    if not news:
        abort(404)
    return render_template(
        'news.html',
        news=news,
    )


@blueprint.route('/<int:read_time>')
def filter_by_read_time(read_time):
    title = 'Новости'
    if read_time == 0:
        return redirect(url_for('news.index'))
    match_ = {5: 'S', 10: 'M', 20: 'L'}
    posts = News.query.filter(News.read_time == match_[read_time]).order_by(News.date.desc()).all()
    news = []
    if current_user.is_authenticated:
        favs_news = Favorite.query.filter(Favorite.user_id == current_user.id)
        for n in favs_news:
            news.append(n.news_id)
    print(news)
    return render_template(
        'index.html',
        title=title,
        posts=posts,
        favs=news,
    )

webapp/user/views.py
"""
В данном файле реализованы основные функции, связанные с работой с пользователем: регистрация пользователя,
авторизация пользователя, выход из аккаунта, добавление новости в избранное, а также отображение всех новостей,
добавленных в избранное
"""

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_user, logout_user
from webapp.db import db
from webapp.news.models import News
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import Favorite, User

blueprint = Blueprint('user', __name__)


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    # проверка корректности заполнения формы для регистрации пользователя: совпадения пароля в полях "password" и
    # "confirm_password", а также уникальности имени пользователя
    if request.method == 'POST':
        if form.validate_on_submit():
            existing_user = User.query.filter_by(username=form.username.data).first()
            if existing_user:
                flash('Такое имя пользователя занято')
                return redirect(url_for('user.register'))
            new_user = User(username=form.username.data)
            new_user.set_password(form.password.data)
            db.session.add(new_user)
            db.session.commit()
            flash('Регистрация прошла успешно!')
            return redirect(url_for('user.login'))
        else:
            flash('Пароли не совпадают!')
    # отрисовка нужной страницы на сайте
    return render_template('register.html', form=form, title='Регистрация')


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if not current_user.is_anonymous:
        return redirect(url_for('news.index'))
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember_me = form.remember_me.data

        user = User.query.filter_by(username=username).first()
        # проверка совпадения введённого имени пользователя и пароля, сохранённых в базе данных
        if user and user.check_password(password):
            flash('Авторизация прошла успешно')
            login_user(user, remember=remember_me)
            return redirect(url_for('news.index'))
        flash('Неверное имя пользователя или пароль')
    return render_template('login.html', form=form)


@blueprint.route('/logout')
def logout():
    # выход из аккаунта пользователя
    if current_user.is_anonymous:
        return redirect(url_for('news.index'))
    logout_user()
    return redirect(url_for('news.index'))


@blueprint.route('/add_to_favorites/<int:news_id>')
def add_to_favorites(news_id):
    # проверка, вошёл ли пользователь в свой аккаунт - функция добавления в избранное доступна только авторизованным
    # пользователям
    if current_user.is_anonymous:
        return redirect(url_for('user.login'))

    check_fav = Favorite.query.filter(Favorite.user_id == current_user.id).filter(Favorite.news_id == news_id).first()
    # если пользователь уже добавлял новость в избранное - значит, он хочет её удалить из избранного, реализуем это
    if check_fav:
        db.session.delete(check_fav)
        db.session.commit()
        flash('Страница успешно удалена из избранного!')
    # иначе добавляем новость в избранное
    else:
        favorite = Favorite(
            user_id=current_user.id,
            news_id=news_id,
        )
        db.session.add(favorite)
        db.session.commit()
        flash('Страница успешно добавлена в избранное!')
    if 'fav' in request.referrer:
        return redirect(url_for('user.favorites'))
    return redirect(request.referrer)


@blueprint.route('/favorites')
def favorites():
    # просмотр всех новостей, добавленных пользователем в избранное
    favorites = Favorite.query.filter(Favorite.user_id == current_user.id).all()
    posts = News.query.all()
    news = []
    for f in favorites:
        news.append(f.news_id)
    return render_template('favorites.html', posts=posts, favs=news)

webapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <style type="text/css"s>
        .tm-user-info__username {
          font-weight: bold;
          font-size: 50px;
          background-color: antiquewhite;
          text-decoration: none;
          color: midnightblue;
          padding: 10px;
        };
    </style>
    <style>
        .authors {
          font-weight: bold;
          font-size: 50px;
          background-color: antiquewhite;
          text-decoration: none;
          color: midnightblue;
          padding: 10px;
        };
    </style>
    <style>
      .news-content img {
          width: 100%;
          height: 100%;
          object-fit: cover;
        };
    </style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{{ url_for('news.index') }}">Главная</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if current_user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('user.favorites') }}">Избранное</a>
          </li>
          {% endif %}
          <li class="nav-item active">
            {% if current_user.is_authenticated %}
              <a class="nav-link" href="{{ url_for('user.logout') }}">Выйти</a>
            {% else %}
              <a class="nav-link" href="{{ url_for('user.login') }}">Войти</a>
            {% endif %}
          </li>
        </ul>
      </div>
    </nav>
    <div class="row">
      <div class="col-4"></div>
      <div class="col-4">
          {% with messages = get_flashed_messages() %}
          {% if messages %}
              {% for message in messages %}
                <div class="alert alert-warning" role="alert">
                  {{ message }}
                </div>
              {% endfor %}
          {% endif %}
        {% endwith %}
      </div>
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

webapp/templates/favorites.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
    <div class="col-2"></div>
    <div class="col-6">

        <h1>Мои избранные страницы:</h1>
        <ul>
            {% for post in posts %}
            {% if post.id in favs %}
                <p>{{ post.date.strftime('%d %B, %H:%M') }}<small>{{ post.time }}</small><a href="{{ url_for('user.add_to_favorites', news_id=post.id) }}">
                    <img style="margin-left: 10px;" src="./static/images/like.png" width="16px" height="16px"></a><br></p>
                <h5><a href="{{ url_for('news.news_index', news_id=post.id) }}" style="text-decoration: none;color:midnightblue">{{ post.title }}</a></h5>
                <hr style="color:midnightblue">
            {% endif %}
            {% endfor %}
        </ul>
{% endblock %}

webapp/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
  <div class="col-2"></div>
  <div class="col-6">
    <p><b>Время чтения:</b>
      <a style="text-decoration: none;color:midnightblue" href="{{ url_for('news.filter_by_read_time', read_time=0) }}">Любое</a> | <a style="text-decoration: none;color:midnightblue" href="{{ url_for('news.filter_by_read_time', read_time=5) }}">До 5 минут</a> | <a style="text-decoration: none;color:midnightblue" href="{{ url_for('news.filter_by_read_time', read_time=10) }}">От 5 до 10 минут</a> | <a style="text-decoration: none;color:midnightblue;" href="{{ url_for('news.filter_by_read_time', read_time=20) }}">Более 10 минут</a>
    </p>
  </div>
</div>
    <div class="row">
        <div class="col-2"></div>
        <div class="col-6">
            {% for post in posts %}
                <p>{{ post.date.strftime('%d-%m-%Y, %H:%M') }}<small>{{ post.time }}</small>
                  <a href="{{ url_for('user.add_to_favorites', news_id=post.id) }}">
                  {% if post.id not in favs %}
                    <img src="./static/images/unlike.png" width="16px" height="16px">
                  {% else %}
                    <img src="./static/images/like.png" width="16px" height="16px">
                  {% endif %}
                  </a></p>
                <h5><a href="{{ url_for('news.news_index', news_id=post.id) }}" style="text-decoration: none;color:midnightblue">{{ post.title }}</a></h5>
                <hr style="color:midnightblue">
            {% endfor %}
        </div>
{% endblock %}

webapp/templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
  <div class="col-4"></div>
  <div class="col-4">
  <h2>Форма логина</h2>
  <form method="POST" action="{{ url_for('user.login') }}">
    {{ form.csrf_token }}
    <div class="form-group">
      {{ form.username.label }} {{ form.username }}
    </div>
    <div class="form-group">
      {{ form.password.label }} {{ form.password }}
    </div>
    <div class="form-group form-check">
      {{ form.remember_me() }} {{ form.remember_me.label(class_='form-check-label') }}
    </div>
    <div>
      {{ form.submit }}
    </div>
       <a href="{{ url_for('user.register') }}">Зарегистрироваться</a>
  </form>
  </div>
</div>
{% endblock %}

webapp/templates/news.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8 news-content">
            {{ news.text|safe }}
        </div>
{% endblock %}

webapp/templates/register.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
  <div class="col-4"></div>
  <div class="col-4">
  <h2>Registration Form</h2>
  <form method="POST" action="{{ url_for('user.register') }}">
    {{ form.csrf_token }}
    <div class="form-group">
      {{ form.username.label }} {{ form.username }}
    </div>
    <div class="form-group">
      {{ form.password.label }} {{ form.password }}
    </div>
    <div class="form-group">
      {{ form.confirm_password.label }} {{ form.confirm_password }}
    </div>
    <div>
      {{ form.submit }}
    </div>
  </form>
  </div>
</div>
{% endblock %}